spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiro_db
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
  session:
    store-type: REDIS
  jpa:
    hibernate:
      ddl-auto: none
  http:
    encoding:
      force: true

